import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/app/header'
import Footer from "./footer";
import NavBar from "./navbar";

export const metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <body >
      <NavBar />
      {children}
      <Footer />
      </body>
    </html>
  );
}
